development:
  GMAIL_USERNAME: "Your Gmail Username"
  GMAIL_PASSWORD: "Your Gmail Password"
  CRUNCHBASE_API: "Your Crunchbase API Key"


test:
  GMAIL_USERNAME: "Your Gmail Username"
  GMAIL_PASSWORD: "Your Gmail Password"
  CRUNCHBASE_API: "Your Crunchbase API Key"

production:
  GMAIL_USERNAME: "Your Gmail Username"
  GMAIL_PASSWORD: "Your Gmail Password"
  CRUNCHBASE_API: "Your Crunchbase API Key"
  SECRET_TOKEN:		"Your Secret Token"